language: node_js
node_js: stable
sudo: false
dist: trusty

cache: npm

before_install:
  - npm install -g npm@6
  - npm install
  - npm install -g codecov

install:
  - npm ci

script:
  - npm t
  - codecov

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
