language: node_js
node_js: stable
dist: trusty

cache: npm

before_install:
  - npm install -g npm@6
  - npm install
  - npm install -g codecov

install:
  - npm ci

script:
  - npm t
  - codecov

deploy:
  - provider: script
    cleanup: true
    script:
      - npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
